### ISSUE TITLE
Haxestudio closes/crashes everytime I create a function

### ISSUE THREAD

**Issue by micadeyeye** [misterpah/Haxe-Studio#54]
Hello guys, 
Does anyone know why HAXEstudio crashes anytime I  type a "("?
 This is the line that causes my project to close.
 [13733:1227/181848:INFO:CONSOLE(337)] "Uncaught SyntaxError: Invalid regular expression: /)/: Unmatched ')'", source: file:///opt/packages/HaxeStudio/bin/index.html# (337)
 
Haxe closes a project everytime I try to create a function, say "public static function Test ()" in the editor. I am using HaxeStudio ver 0.4.4

--

**Comment by misterpah** [comment]
0.4.4 makes these radical changes to source code & this is a very bad bug.
0.5 will fixes this weird bug(s)..

if you're feeling adventurous enough, 
pull from the "future" branch. 
it's much-much-much better than version 0.4.4
