### ISSUE TITLE
HaxeStudio web site is not working.

### ISSUE THREAD

**Issue by musou1500** [misterpah/Haxe-Studio#56]
I find [HaxeStudio website](http://www.haxestudio.com/) is not working.

**Comment by misterpah** [comment]
yes, there's some error with my hosting (php can't run on it).
PHP is important because i wanted to roll out new patch via one-click update.

**Comment by musou1500** [comment]
I understood.
But I think this site should not publicly until server configuration is not finished .

**Comment by misterpah** [comment]
I agree..
btw, it fixed !
