### ISSUE TITLE
The iIDE is damn ugly

### ISSUE THREAD

**Issue by Aare-** [misterpah/Haxe-Studio#57]
The orange colour of the ide is hurting my eyes when working with this otherwise very promising ide.
Could you mabye go with more darkish colours? The colour sheme from intelliJ darcula theme would be perfect.

**Comment by musou1500** [comment]
which version do you use?

**Comment by Aare-** [comment]
The latest one (I guess).
Pic: 
![bez tytulu](https://cloud.githubusercontent.com/assets/2124653/5989384/89562b98-a986-11e4-9622-2ba7c3ad65cd.png)

**Comment by musou1500** [comment]
Hmmm...
I can't resolve this because I am not a contributor...
But, Haxestudio use a bootstrap(css framework).
So, changing theme is a not difficult.

**Comment by Aare-** [comment]
Glad to hear that :) I get the orange connection to the haxe logo - it just doesn't work well imho for the interface.

**Comment by misterpah** [comment]
agreed. that's a damn ugly theme.. :p
i was experimenting with the LESS color scheme and forget to change it back.. 
expect plesant color on 0.5.1

**Comment by misterpah** [comment]
hi all.
we've update to a much better theme.
get your latest patch [here](http://haxestudio.com/patch.php)
![v0.5.1](http://i.imgur.com/pEGb8zA.png)
