### ISSUE TITLE
Close new project dialog when user clicks create button(if there are no errors)

### ISSUE THREAD

**Issue by as3boyan** [misterpah/Haxe-Studio#59]
Close new project dialog when user clicks create button(if there are no errors)
And open project in IDE after creation

This one may be more complicated, maybe `global` object may help
https://github.com/nwjs/nw.js/wiki/Transfer-objects-between-window-and-node#one-node-to-multiple-windows

**Comment by misterpah** [comment]
mechanism changed in d723f46647f9a310cbf5e70b500fc240e0dffb3d.
