### ISSUE TITLE
haxelib distribution

### ISSUE THREAD

**Issue by as3boyan** [misterpah/Haxe-Studio#61]
patch system is nice, I understand that you want to make own system, but maybe consider haxelib distribution? Installation can be even easier. It's like one script, zip some folders, publish to haxelib and you're good to go

**Comment by misterpah** [comment]
haxelib is great distribution mechanism.
But, I afraid if Haxe Studio is available in Haxelib, people will assume it's written in Haxe. 

Then they feel cheated when they discover that Haxe Studio are written in multiple languages (standard JS, Node, jQuery, neko, php )

so, to prevent this from happening in the community, I won't be distributing Haxe Studio using haxelib.
