### ISSUE TITLE
OSX HD name with space fail

### ISSUE THREAD

**Issue by MatthijsKamstra** [misterpah/Haxe-Studio#63]
I worked around the "haxe-studio-update.command" and did the same for "haxe-studio.command" but then it failed again because it couldn't find the path to the file.

This behavior is caused by a harddisk name with a space in it: "Data HD".

**Comment by misterpah** [comment]
thank you for reporting.
i'll look at it now

**Comment by misterpah** [comment]
OSX bash is much difference compared to Linux bash. :sweat_smile: 
hence, the bug.
after 3 hours, i think i fixed it.

![osx](https://cloud.githubusercontent.com/assets/2442459/6221778/4611608c-b683-11e4-89c2-f78654181046.png)

**Comment by MatthijsKamstra** [comment]
I can confirm that it works on OSX, nice! thx!
